### ISSUE TITLE
Symbol not found: __ZN9CPPExtern4postEPKcz

### ISSUE THREAD

**Issue by n1ckfg** [badgeek/fux_kinect#2]
When I try to load the example patch, I get the following:

... couldn't create
/Applications/Pd-extended.app/Contents/Resources/extra/fux_kinect/fux_kinect.pd_darwin: dlopen(/Applications/Pd-extended.app/Contents/Resources/extra/fux_kinect/fux_kinect.pd_darwin, 10): Symbol not found: __ZN9CPPExtern4postEPKcz
  Referenced from: /Applications/Pd-extended.app/Contents/Resources/extra/fux_kinect/fux_kinect.pd_darwin
  Expected in: dynamic lookup

...any advice?

**Comment by coreyker** [comment]
I just compiled fux_kinect and I get the exact same error... I'm not sure what the cause is.
